[package]
name = "quilla-js"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
quilla = { path = "../core", features = ["serde"] }
js-sys = "0.3"
wasm-bindgen = "0.2"
serde = { version = "1", default-features = false, features = [
  "std",
  "derive",
] }
ts-rs = "12"
serde-wasm-bindgen = "0.6"
bitvec = { version = "1.0", default-features = false }
num-complex = "0.4"
