[package]
name = "quilla"
version = "0.1.0"
edition = "2024"

[features]
default = ["std"]
std = [
  "bitvec/std",
  "ndarray/std",
  "num-complex/std",
  "num-traits/std",
  "rand/std",
  "rand/std_rng",
  "rand/sys_rng",
  "rand/thread_rng",
]

[dependencies]
bitvec = { version = "1.0", default-features = false, features = ["alloc"] }
ndarray = { version = "0.17", default-features = false }
num-complex = { version = "0.4", default-features = false }
num-traits = { version = "0.2", default-features = false, features = ["libm"] }
rand = { version = "0.10", default-features = false }

[dev-dependencies]
pretty_assertions = { version = "1.4", default-features = false, features = [
  "alloc",
] }
