[package]
name = "quilla"
version = "0.1.0"
edition = "2024"

[features]
default = ["std"]
std = [
  "bitvec/std",
  "num-complex/std",
  "num-traits/std",
  "rand/std",
  "serde/std",
]
libm = ["num-complex/libm", "num-traits/libm"]
serde = ["dep:serde", "num-complex/serde"]

[dependencies]
bitvec = { version = "1.0", default-features = false, features = ["alloc"] }
num-complex = { version = "0.4", default-features = false }
num-traits = { version = "0.2", default-features = false }
rand = { version = "0.10", default-features = false }
serde = { version = "1", default-features = false, features = [
  "derive",
  "alloc",
], optional = true }

[dev-dependencies]
pretty_assertions = { version = "1.4", default-features = false, features = [
  "alloc",
] }
